name: Deploy

on:
  push:
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
    branches:
      - main

jobs:
  CD:
    runs-on: ubuntu-latest

    steps:
      - name: Download repository
        uses: actions/checkout@v3

      - name: Install docker compose
        uses: KengoTODA/actions-setup-docker-compose@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: docker compose version

      - name: Download lint script
        run: |
          curl -o "lint.sh" "https://raw.githubusercontent.com/MythosCode/.github/main/docker-compose/lint.sh"
          chmod +x ./lint.sh

      - name: Run lint
        run: |
          ./lint.sh

      - name: Run build
        run: |
          ./build.sh    